name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
